name: mdenv
channels:
  - conda-forge
  - defaults
dependencies:
  - atomicwrites
  - attrs
  - backcall
  - blas
  - bleach
  - ca-certificates
  - certifi
  - cycler
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - freetype
  - gettext
  - gitdb2
  - gitpython
  - glib
  - icu
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - libclang
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libgfortran
  - libiconv
  - libllvm8
  - libpng
  - libsodium
  - llvm-openmp
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - more-itertools
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - nspr
  - nss
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pluggy
  - prometheus_client
  - prompt_toolkit
  - ptyprocess
  - py
  - pygments
  - pyparsing
  - pyqt
  - pyrsistent
  - pytest
  - python
  - python-dateutil
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - readline
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - six
  - smmap2
  - sqlite
  - terminado
  - testpath
  - tk
  - tornado
  - tqdm
  - traitlets
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xz
  - zeromq
  - zipp
  - zlib
  - pip:
    - pyqt5-sip
    - pyqtwebengine
    - seglearn

